vapor/Controllers/AboutPageController.cs
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using vapor.Data;
using vapor.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Http;

namespace vapor.Controllers
{
    public class AboutPageController : Controller
    {
        [AllowAnonymous]
        public IActionResult Index()
        {
            return View();
        }
    }
}

vapor/Controllers/AnalysisController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using vapor.Data;

namespace vapor.Controllers
{
    [Authorize(Roles = "Admin")]
    public class AnalysisController : Controller
    {

        private readonly vaporContext _context;

        public AnalysisController(vaporContext context)
        {
            _context = context;

        }
        // GET: AnalysisController
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult GetGamesAnalysis()
        {
            var searchResult = from g in _context.Game
                               select new { date = g.releaseDate.Date };

            return Json(searchResult);
        }

        public ActionResult GetOrdersAnalysis()
        {
            var searchResult = from order in _context.Order
                               select new { date = order.date.Date };

            return Json(searchResult);
        }

        public ActionResult GetGameReviewAnalysis()
        {
            /* (from a in context.Accounts
               join c in context.Clients on a.UserID equals c.UserID
               where c.ClientID == yourDescriptionObject.ClientID
               select a.Balance)
             */

            var searchResult = from game in _context.Game
                               join review in _context.Review on game.id equals review.gameId into groupReviews
                               from groupReview in groupReviews.DefaultIfEmpty()
                               group groupReview by game.name into groupReviewes
                               select new
                               {
                                   name = groupReviewes.Key,
                                   averageRating = groupReviewes.Average(r => r == null ? 0 : r.rating),
                               };

            return Json(searchResult);
        }
    }
}

vapor/Controllers/GamesController.cs
using System;
using System.Collections.Generic;
using System.Dynamic;
using System.IO;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using vapor.Data;
using vapor.Models;
using System.ServiceModel.Syndication;
using System.Xml;
using vapor.services;

namespace vapor.Controllers
{
    public class GamesController : Controller
    {
        private readonly vaporContext _context;
        private twitter _twitterService;

        public GamesController(vaporContext context, twitter twitterService)
        {
            _context = context;
            _twitterService = twitterService;
        }

        // GET: Games
        [AllowAnonymous]
        public async Task<IActionResult> Index()
        {

            var games = _context.Game
                .Include(g => g.genres)
                .Include(g => g.developer)
                .Include(g => g.images)
                .Select(g => new Game
                {
                    id = g.id,
                    name = g.name,
                    developer = g.developer,
                    genres = (ICollection<Genre>)g.genres.Take(4),
                    images = new List<GameImage>()
                    {
                        g.images.Select(i => new GameImage { id = i.id }).First()
                    }
                }).ToListAsync();


            dynamic model = new ExpandoObject();
            model.games = await games;

            var genres = _context.Genre.ToArrayAsync();
            model.genres = await genres;

            var developers = _context.Developer.ToArrayAsync();
            model.developers = await developers;

            return View(model);
        }

        [HttpGet]
        public List<String> getNews()
        {
            var url = "http://feeds.feedburner.com/ign/news";
            using var reader = XmlReader.Create(url);
            var feed = SyndicationFeed.Load(reader);
            List<String> newsTitles = new List<String>();
            foreach (SyndicationItem item in feed.Items)
            {
                newsTitles.Add(item.Title.Text);
            }
            return newsTitles;
        }

        // GET: Games/Details/5
        [AllowAnonymous]
        public async Task<IActionResult> Details(string id)
        {
            dynamic model = new ExpandoObject();
            if (id == null)
            {
                return NotFound();
            }

            var loadedGame = await _context.Game
                .Include(g => g.genres)
                .Include(g => g.developer)
                .Select(game => new
                {
                    game,
                    game.developer,
                    images = game.images.Select(i => new GameImage { id = i.id }).ToList()
                })
                .FirstOrDefaultAsync(g => g.game.id == id);

            if (loadedGame == null)
            {
                return NotFound();
            }

            loadedGame.game.images = loadedGame.images;
            loadedGame.game.developer = loadedGame.developer;
            model.game = loadedGame.game;
            loadedGame.game.images.Count();
            string currUserID = HttpContext.Session.GetString("userid");

            var currCustomer = await _context.User
                    .Where(u => u.Id == currUserID)
                    .Select(u => u.customer)
                    .FirstOrDefaultAsync();

            var customerReview = await _context.Review
                .Where(r => r.cusotmer == currCustomer)
                .FirstOrDefaultAsync();

            model.currentCustomer = currCustomer;
            model.customerReview = customerReview;

            /*var otherReviews = await _context.Review
                .Where(r => r.cusotmer != currCustomer)
                .ToListAsync();*/

            var otherReviews = _context.Review
                .Where(r => r.gameId.Equals(id) && r.cusotmer != currCustomer)
                .OrderByDescending(r => r.lastUpdate)
                .Select(r => new Review
                {
                    id = r.id,
                    gameId = r.gameId,
                    comment = r.comment,
                    rating = r.rating,
                    writtenAt = r.writtenAt,
                    lastUpdate = r.lastUpdate,
                    cusotmer = new Customer
                    {
                        name = r.cusotmer.name
                    }
                });

            model.reviews = otherReviews;

            var currUserReview = _context.Review
                .Where(r => r.gameId.Equals(id) && r.cusotmer.Equals(currCustomer))
                .Select(r => new Review
                {
                    id = r.id,
                    gameId = r.gameId,
                    comment = r.comment,
                    rating = r.rating,
                    writtenAt = r.writtenAt,
                    lastUpdate = r.lastUpdate,
                    cusotmer = new Customer
                    {
                        name = r.cusotmer.name
                    }
                })
                .FirstOrDefaultAsync();

            model.currUserReview = await currUserReview;

            var currCustomerOrder = await _context.Order
            .Include(o => o.customer)
            .Where(o => o.customer == currCustomer && o.gameId==id)
            .FirstOrDefaultAsync();

            model.currCustomerOrder = currCustomerOrder;

            var avarageRate = await _context.Review
                .Where(r => r.gameId.Equals(id))
                .GroupBy(r => r.gameId)
                .Select(gb => gb.Average(r => r.rating))
                .FirstOrDefaultAsync();


            model.avarageRate = avarageRate;


            return View(model);
        }
        [Authorize(Roles = "Admin,Developer")]
        // GET: Games/Create
        public IActionResult Create()
        {
            ViewBag.genreSelectList = new SelectList(_context.Genre, nameof(Genre.id), nameof(Genre.name)).ToList();
            return View();
        }

        // POST: Games/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("id,price,name,description")] Game game,
                                                List<String> newGenreIds,
                                                List<IFormFile> newImages)
        {

            if (ModelState.IsValid)
            {
                GameImage gameImage;
                game.images = new List<GameImage>();
                game.releaseDate = DateTime.Now;

                // Saves all the new images
                foreach (IFormFile image in newImages)
                {
                    using (var ms = new MemoryStream())
                    {
                        image.CopyTo(ms);
                        byte[] fileBytes = ms.ToArray();

                        gameImage = new GameImage();
                        gameImage.fileBase64 = Convert.ToBase64String(fileBytes);
                        gameImage.fileContentType = image.ContentType;
                        game.images.Add(gameImage);
                    }
                }

                // Connects between the game to the proper developer
                string currUserID = HttpContext.Session.GetString("userid"); ;
                var currDev = await _context.User
                    .Where(u => u.Id == currUserID)
                    .Select(u => u.developer)
                    .FirstOrDefaultAsync();

                game.developerId = currDev.id;
                game.developer = currDev;

                // Connects between the game to the game genres
                var genresList = await _context.Genre.Where(g => newGenreIds.Contains(g.id)).ToListAsync();
                game.genres = genresList;

                _context.Add(game);
                await _context.SaveChangesAsync();
                _twitterService.postTweet(game);
                return RedirectToAction(nameof(Index));
            }
            ViewData["developerId"] = new SelectList(_context.Developer, "id", "id", game.developerId);
            return View(game);
        }


        [HttpGet]
        public async Task<ActionResult> GetGameImage(string gameImageId)
        {
            if (gameImageId == null)
            {
                return NotFound();
            }

            GameImage gameImage = await _context.GameImage.FirstOrDefaultAsync(gi => gi.id == gameImageId);

            if (gameImage == null)
            {
                return NotFound();
            }

            byte[] fileBytes = Convert.FromBase64String(gameImage.fileBase64);
            return this.File(fileBytes, gameImage.fileContentType);
        }

        [HttpGet]
        public async Task<ActionResult> GetGameImageByGameId(string gameId)
        {
            if (gameId == null)
            {
                return NotFound();
            }

            GameImage gameImage = await _context.GameImage.FirstOrDefaultAsync(gi => gi.gameID == gameId);

            if (gameImage == null)
            {
                return NotFound();
            }

            byte[] fileBytes = Convert.FromBase64String(gameImage.fileBase64);
            return this.File(fileBytes, gameImage.fileContentType);
        }
        [Authorize(Roles = "Admin,Developer")]
        // GET: Games/Edit/5
        public async Task<IActionResult> Edit(string id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var loadedGame = await _context.Game
                .Include(g => g.genres)
                .Select(game => new

vapor/Controllers/GenresController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using vapor.Data;
using vapor.Models;

namespace vapor.Controllers
{
    public class GenresController : Controller
    {
        private readonly vaporContext _context;

        public GenresController(vaporContext context)
        {
            _context = context;
        }

        // GET: Genres
        [AllowAnonymous]
        public async Task<IActionResult> Index()
        {
            return View(await _context.Genre.ToListAsync());
        }

        [HttpGet]
        [AllowAnonymous]
        public async Task<IActionResult> All()
        {
            return Json(await _context.Genre.ToListAsync());
        }

        // GET: Genres/Details/5
        public async Task<IActionResult> Details(string id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var genre = await _context.Genre
                .FirstOrDefaultAsync(m => m.id == id);
            if (genre == null)
            {
                return NotFound();
            }

            return View(genre);
        }

        // GET: Genres/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Genres/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("id,name")] Genre genre)
        {
            if (ModelState.IsValid)
            {
                _context.Add(genre);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(genre);
        }

        // GET: Genres/Edit/5
        public async Task<IActionResult> Edit(string id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var genre = await _context.Genre.FindAsync(id);
            if (genre == null)
            {
                return NotFound();
            }
            return View(genre);
        }

        // POST: Genres/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(string id, [Bind("id,name")] Genre genre)
        {
            if (id != genre.id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(genre);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!GenreExists(genre.id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(genre);
        }

        // GET: Genres/Delete/5
        public async Task<IActionResult> Delete(string id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var genre = await _context.Genre
                .FirstOrDefaultAsync(m => m.id == id);
            if (genre == null)
            {
                return NotFound();
            }

            return View(genre);
        }

        // POST: Genres/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(string id)
        {
            var genre = await _context.Genre.FindAsync(id);
            _context.Genre.Remove(genre);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool GenreExists(string id)
        {
            return _context.Genre.Any(e => e.id == id);
        }
    }
}

vapor/Views/Shared/_Layout.cshtml
@using Microsoft.AspNetCore.Http
@inject IHttpContextAccessor HttpContextAccessor
@{
    var username = HttpContextAccessor.HttpContext.Session.GetString("username");
    var loginText = "";
    if (username == null || username == "")
    {
        loginText = "login!";
    }
    else
    {
        loginText = "Hello " + @username + " !";
    }
}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - vapor</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
    <link rel="stylesheet" href="~/css/news.css" />
    <link rel="stylesheet" href="~/css/Users/UsersIndex.css" />
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.5.0/font/bootstrap-icons.css">
</head>
<body class="text-white">
    <header id="site__header" >
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light  text-white border-bottom box-shadow mb-3">
            <div  class="container text-white">
                <a class="navbar-brand  text-white" asp-area="" asp-controller="Games" asp-action="Index">vapor</a><i class="bi bi-controller"></i>

                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-white" asp-area="" asp-controller="Reviews" asp-action="">Reviews</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-white" asp-area="" asp-controller="Developers" asp-action="">Developers</a>
                        </li>
                        @if (User.IsInRole("Admin"))
                        {
                            <li class="nav-item">
                                <a class="nav-link text-white" asp-area="" asp-controller="Customers" asp-action="">Customers</a>
                            </li>
                        }
                        <li class="nav-item">
                            <a class="nav-link text-white" asp-area="" asp-controller="Genres" asp-action="">Genres</a>
                        </li>
                        @if (User.IsInRole("Admin") || User.IsInRole("Developer") || User.IsInRole("Customer"))
                        {
                            <li class="nav-item">
                                <a class="nav-link text-white" asp-area="" asp-controller="Orders" asp-action="">Orders</a>
                            </li>
                        }
                        @if (User.IsInRole("Admin"))
                        {
                            <li class="nav-item">
                                <a class="nav-link text-white" asp-area="" asp-controller="Users" asp-action="">Users</a>
                            </li>
                        }
                        @if (User.IsInRole("Admin"))
                        {
                            <li class="nav-item">
                                <a class="nav-link text-white" asp-area="" asp-controller="Analysis" asp-action="">Analysis</a>
                            </li>
                        }

                        @if (User.IsInRole("Admin"))
                        {
                            <li class="nav-item">
                                <a class="nav-link text-white" asp-area="" asp-controller="MapCoordinates" asp-action="">Map</a>
                            </li>
                        }
                        @if (User.IsInRole("Customer"))
                        {
                            <li class="nav-item">
                                <a class="nav-link text-white" asp-area="" asp-controller="Orders" asp-action="Create">Cart</a>
                            </li>
                        }
                        <li class="nav-item">
                            <a class="nav-link text-white" asp-area="" asp-controller="AboutPage" asp-action="">About us</a>
                        </li>

                    </ul>
                    <span class="navbar-text text-white">
                        <a class="nav-link text-white" asp-area="" asp-controller="Users" asp-action="Logout">@loginText</a>
                    </span>
                </div>
            </div>
        </nav>
    </header>
    <div id="site__body"  class="container-fluid  text-white">
        <div class="row flex-xl-nowrap">
            <div class="col-md-3 col-xl-2 bd-sidebar">
                @RenderSection("sidebar", required: false)
            </div>
            <main role="main" class="pb-3 col-md-9 col-xl-8 py-md-3 pl-md-5 bd-content">
                @RenderBody()
            </main>
            <nav class="d-none d-xl-block col-xl-2 bd-toc">
                @*placeholder for right side nav*@
            </nav>
        </div>
    </div>

    <div class="container align-items-end text-muted  text-white">
        @await RenderSectionAsync("Alerts", required: false)
    </div>

    <footer id="site__footer" class="border-top footer text-muted  text-white">
        <div class="container  text-white">
            &copy; 2021 - vapor 
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
    @await RenderSectionAsync("News", required: false)
</body>
</html>

vapor/Views/Shared/_LoginLayout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Vapor</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body class="bg-dark text-white">    
    <div class="container text-center bg-dark text-white">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>