vapor/Models/User.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Threading.Tasks;

namespace vapor.Models
{
    public enum UserType
    {
        Customer,
        Developer,
        Admin
    }

    public class User
    {
        [DatabaseGenerated(DatabaseGeneratedOption.Identity)]
        public String Id { get; set; }

        [Required]
        public string Username { get; set; }

        [Required]
        [DataType(DataType.Password)]
        public string Password { get; set; }

        public UserType Type { get; set; } = UserType.Customer;
         
        public Customer customer { get; set; }

        public String customerID { get; set; }

        public Developer developer { get; set; }

        public String developerID { get; set; }



    }
}

vapor/Controllers/DevelopersController.cs
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using vapor.Data;
using vapor.Models;
using Microsoft.AspNetCore.Authorization;
using vapor.services;

namespace vapor.Controllers
{

    public class DevelopersController : Controller
    {
        private readonly vaporContext _context;
        private twitter _twitterService;

        public DevelopersController(vaporContext context, twitter twitterService)
        {
            _context = context;
            _twitterService = twitterService;
        }

        [AllowAnonymous]
        public async Task<IActionResult> Index()
        {
            return View(await _context.Developer.ToListAsync());
        }

        public async Task<IActionResult> All()
        {
            /*byte[] fileBytes = Convert.FromBase64String(gameImage.fileBase64);
            return this.File(fileBytes, gameImage.fileContentType);
*/

            return Json(await _context.Developer.ToListAsync());
        }
        public async Task<IActionResult> Id(String id)
        {
            /*byte[] fileBytes = Convert.FromBase64String(gameImage.fileBase64);
            return this.File(fileBytes, gameImage.fileContentType);
*/
            if (id == null)
            {
                return NotFound();
            }

            var developer = await _context.Developer
                .FirstOrDefaultAsync(m => m.id == id);
            if (developer == null)
            {
                return NotFound();
            }

            return Json(await _context.Developer.ToListAsync());
        }

        //[AllowAnonymous][Authorize(Roles = "Admin,Developer")]
        [AllowAnonymous]
        // GET: Developers/Details/5
        public async Task<IActionResult> Details(string id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var developer = await _context.Developer
                .Where(d => d.id == id)
                .Include(d => d.games).ThenInclude(g => g.reviews)
                .Include(d => d.games).ThenInclude(g => g.genres)
                .FirstOrDefaultAsync(m => m.id == id);
            if (developer == null)
            {
                return NotFound();
            }

            return View(developer);
        }

        [Authorize(Roles = "Admin")]
        // GET: Developers/Create
        public IActionResult Create()
        {
            return View();
        }
        [Authorize(Roles = "Admin")]
        // POST: Developers/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [Authorize]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("id,name,avatar")] Developer developer, IFormFile developerAvater)
        {
            if (ModelState.IsValid)
            {
                using (var ms = new MemoryStream())
                {
                    developerAvater.CopyTo(ms);
                    byte[] fileBytes = ms.ToArray();
                    developer.avatar = Convert.ToBase64String(fileBytes);
                    developer.fileContentType = developerAvater.ContentType;
                }
                _context.Add(developer);
                await _context.SaveChangesAsync();
                _twitterService.postTweet(developer);
                return RedirectToAction(nameof(Index));
            }


            return View(developer);
        }

        [Authorize(Roles = "Admin")]
        // GET: Developers/Edit/5
        public async Task<IActionResult> Edit(string id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var developer = await _context.Developer.FindAsync(id);
            if (developer == null)
            {
                return NotFound();
            }
            return View(developer);
        }

        [Authorize(Roles = "Admin")]
        // POST: Developers/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(string id, [Bind("id,name,avatar")] Developer developer, IFormFile developerAvater)
        {
            if (id != developer.id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    using (var ms = new MemoryStream())
                    {
                        developerAvater.CopyTo(ms);
                        byte[] fileBytes = ms.ToArray();
                        developer.avatar = Convert.ToBase64String(fileBytes);
                        developer.fileContentType = developerAvater.ContentType;
                    }
                    _context.Update(developer);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!DeveloperExists(developer.id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(developer);
        }
        [Authorize(Roles = "Admin")]
        // GET: Developers/Delete/5
        public async Task<IActionResult> Delete(string id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var developer = await _context.Developer
                .FirstOrDefaultAsync(m => m.id == id);
            if (developer == null)
            {
                return NotFound();
            }

            return View(developer);
        }
        [Authorize(Roles = "Admin")]
        // POST: Developers/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(string id)
        {
            var developer = await _context.Developer.FindAsync(id);
            _context.Developer.Remove(developer);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        [HttpPost]
        [AllowAnonymous]
        public async Task<IActionResult> Search(string devName, string gameName, int numOfGames = 1)
        {
            List<Developer> result = new List<Developer>();

            if (numOfGames == 1)
            {
                if (gameName == null || gameName == "")
                {
                    var developerSeach = _context.Developer
                    .Where(d => ( devName != null && devName != "" ) ? d.name.Contains(devName) : true);

                    result.AddRange(await developerSeach.ToListAsync());
                }
                else
                {
                    var gameSearch = _context.Game
                            .Include(g => g.developer)
                            .Where(g => g.name.Contains(gameName))
                            .Where(g => ( devName != null && devName != "" ) ? g.developer.name.Contains(devName) : true)
                            .Select(d => d.developer);

                    result.AddRange(await gameSearch.ToListAsync());
                }
            }
            else if (numOfGames > 1)
            {
                var numofGameSearchIds = await _context.Game
                    .Include(g => g.developer)
                    .GroupBy(g => g.developerId)
                    .Select(gb => new
                    {
                        developerid = gb.Key,
                        count = gb.Count()
                    })
                    .Where(devId => devId.count >= numOfGames)
                    .Select(gb => gb.developerid)
                    .ToListAsync();

                var devs = _context.Game
                            .Include(g => g.developer)
                            .Where(g => g.name.Contains(gameName))
                            .Where(g => ( devName != null && devName != "" ) ? g.developer.name.Contains(devName) : true)
                            .Select(d => d.developer)
                            .Where(d => numofGameSearchIds.Contains(d.id));

                result.AddRange(await devs.ToListAsync());
            }

            return Json(result);
        }

        [AllowAnonymous]
        [HttpGet]
        public async Task<ActionResult> getDeveloperAvater(string devId)
        {
            if (devId == null)
            {
                return NotFound();
            }

            Developer developer = await _context.Developer.FirstOrDefaultAsync(d => d.id == devId);

            if (developer == null)
            {
                return NotFound();
            }

            byte[] fileBytes = Convert.FromBase64String(developer.avatar);
            return this.File(fileBytes, developer.fileContentType);
        }

        private bool DeveloperExists(string id)
        {
            return _context.Developer.Any(e => e.id == id);
        }
    }
}

vapor/Views/Users/AccessDenied.cshtml
@model vapor.Models.User

@{
    ViewData["Title"] = "AccessDenied";
}
<aside>
    <h1>Oppppsssssi!!!!!</h1>
</aside>
    <h2>You are not authorized to access this page.</h2>

    <a asp-action="Logout">Click here</a> to signin using a different user

vapor/Views/Users/Create.cshtml
@model vapor.Models.User

@{
    ViewData["Title"] = "Create";
}

<h1>Create</h1>

<h4>User</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Username" class="control-label"></label>
                <input asp-for="Username" class="form-control" />
                <span asp-validation-for="Username" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Password" class="control-label"></label>
                <input asp-for="Password" class="form-control" />
                <span asp-validation-for="Password" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Type" class="control-label"></label>
                <select asp-for="Type" class="form-control">
                    <option value="Admin">Admin</option>
                    <option value="Developer">Developer</option>
                    <option value="Customer">Customer</option>
                </select>
                <span asp-validation-for="Type" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="customer.name" class="control-label"></label>
                <input asp-for="customer.name" class="form-control" />
                <span asp-validation-for="customer.name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="customer.email" class="control-label"></label>
                <input asp-for="customer.email" class="form-control" />
                <span asp-validation-for="customer.email" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="customer.firstName" class="control-label"></label>
                <input asp-for="customer.firstName" class="form-control" />
                <span asp-validation-for="customer.firstName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="customer.lastName" class="control-label"></label>
                <input asp-for="customer.lastName" class="form-control" />
                <span asp-validation-for="customer.lastName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="customer.phoneNumber" class="control-label"></label>
                <input asp-for="customer.phoneNumber" class="form-control" />
                <span asp-validation-for="customer.phoneNumber" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a class="btn btn-info" asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

vapor/Views/Users/Delete.cshtml
@model vapor.Models.User

@{
    ViewData["Title"] = "Delete";
}

<h1>Delete</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>User</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Username)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Username)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Password)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Password)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Type)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Type)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="Id" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a class="btn btn-info" asp-action="Index">Back to List</a>
    </form>
</div>

vapor/Views/Users/Details.cshtml
@model vapor.Models.User

@{
    ViewData["Title"] = "Details";
}

<h1>Details</h1>

<div>
    <h4 class="main-title">User</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Username)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Username)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Password)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Password)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Type)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Type)
        </dd>
    </dl>
</div>
<div>
    <a class="btn btn-secondary" asp-action="Edit" asp-route-id="@Model.Id">Edit</a> |
    <a class="btn btn-info" asp-action="Index">Back to List</a>
</div>

vapor/Views/Users/Edit.cshtml
@model vapor.Models.User

@{
    ViewData["Title"] = "Edit";
}

<h1>Edit</h1>

<h4>User</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="Id" />
            <div class="form-group">
                <label asp-for="Username" class="control-label"></label>
                <input asp-for="Username" class="form-control" />
                <span asp-validation-for="Username" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Password" class="control-label"></label>
                <input asp-for="Password" class="form-control" />
                <span asp-validation-for="Password" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Type" class="control-label"></label>
                <select asp-for="Type" class="form-control">
                    <option value="Admin">Admin</option>
                    <option value="Developer">Developer</option>
                    <option value="Customer">Customer</option>
                </select>
                <span asp-validation-for="Type" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a class="btn btn-info" asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

vapor/Views/Users/Index.cshtml
@model IEnumerable<vapor.Models.User>

@{
    ViewData["Title"] = "Index";
}

<div class="row profile-container">
    @foreach (var item in Model)
    {


        <div class="profile-card" style="margin:1.5rem;">
            @if (item.Type == UserType.Developer)
            {
                <img class="profile-img" src=@Url.Action("getDeveloperAvater","Developers", new {devId = item.developerID}) alt="Avatar" width="100" height="100">

            }
            else
            {
                <img class="profile-img" src="~/Image/profile.png" alt="Avatar" width="100" height="100">

            }
            <h4><b>@Html.DisplayFor(modelItem => item.Username)</b></h4>
            <p>@Html.DisplayFor(modelItem => item.Type)</p>
            <a class="btn btn-warning w-100" asp-action="Edit" asp-route-id="@item.Id">Edit</a>
            <a class="btn btn-primary w-100" asp-action="Details" asp-route-id="@item.Id">Details</a>
            @if (item.Type == UserType.Customer)
            {
                <a class="btn btn-danger w-100" asp-action="Delete" asp-route-id="@item.Id">Delete</a>
            }

        </div>
    }
</div>

vapor/Views/Users/Login.cshtml
@model vapor.Models.User

@{
    ViewData["Title"] = "Login";
    @*    Layout = "_LoginLayout";*@
}

<h1 class="main-title">Vapor. Conquer The Battlefield </h1>

<hr />
<div class="profile-card">

    <div class="row text-center text-white d-flex justify-content-center">
        <div class="col-md-4 text-center text-white ">
            <form asp-action="Login">
                <div asp-validation-summary="ModelOnly" class="text-danger"></div>
                <div class="form-group">
                    <label asp-for="Username" class="control-label"></label>
                    <input asp-for="Username" class="form-control text-center" />
                    <span asp-validation-for="Username" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label asp-for="Password" class="control-label"></label>
                    <input asp-for="Password" class="form-control" />
                    <span asp-validation-for="Password" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <input type="submit" value="Login" class="btn btn-primary" />
                </div>
            </form>
            @if (ViewBag.Error != null)
            {
                <div class="text-danger">@ViewBag.Error</div>
            }
        </div>
    </div>
    <div class="row text-center text-white register-now__note">
        Not registered?
        <a asp-action="Register" class="register-now__button">
            <button class="btn btn-primary">
                Click here
            </button>

        </a>
        to register As Customer!
    </div>

    <div class="row text-center text-white register-now__note">
        Not registered?
        <a asp-action="RegisterDeveloper" class="register-now__button">
            <button class="btn btn-primary">
                Click here
            </button>
        </a>
        to register As Developer!
    </div>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
    <style>
        .register-now__note {
            margin: 1rem;
        }

        .register-now__button {
            margin-left: 1rem;
            margin-right: 1rem;
        }
    </style>
}

vapor/Views/Users/Register.cshtml
@model vapor.Models.User

@{
    ViewData["Title"] = "Register Customer";
}

<h1>Register a new user</h1>

<div class="row d-flex justify-content-center">
    <div class="col-md-4">
        <form id="register-user">
            <div class="row">
                <div class="form-group">
                    <input type="text" class="form-control" placeholder="First Name" id="register-firstname" name="firstName">
                </div>
            </div>
            <div class="row">
                <div class="form-group">
                    <input type="text" class="form-control" placeholder="Last Name" id="register-lastname" name="lastName" required>
                </div>
            </div>
            <div class="row">
                <div class="form-group">
                    <input type="text" class="form-control" placeholder="User Name" id="register-username" name="Username" required>
                </div>
            </div>
            <div class="row">
                <div class="form-group">
                    <input type="password" class="form-control" placeholder="Password" id="register-password" name="Password">
                </div>
            </div>
            <div class="row">
                <div class="form-group">
                    <input type="password" class="form-control" placeholder="Password Again" id="register-password-again" name="PasswordAgain" required>
                </div>
            </div>
            <div class="row">
                    <select class="form-control" name="type" hidden required>
                        <option value="0">Customer</option>
                    </select>
                    <span class="text-danger"></span>
            </div>
            <div class="row">
                <div class="form-group">
                    <input type="email" class="form-control" placeholder="Email" id="register-email" name="email" required>
                </div>
            </div>
            <div class="row">
                <div class="form-group">
                    <input type="text" class="form-control" placeholder="Phone Number" id="register-phonenumber" name="phoneNumber" required>
                </div>
            </div>
            <div class="form-group">
                <button class="btn btn-primary" id="register-btn">Register</button>
            </div>
        </form>
        <script type="text/javascript">
            window.onload = function () {
                var txtPassword = document.getElementById("register-password");
                var txtConfirmPassword = document.getElementById("register-password-again");
                txtPassword.onchange = ConfirmPassword;
                txtConfirmPassword.onkeyup = ConfirmPassword;

                var txtUsername = document.getElementById("register-username");
                console.log(txtUsername);
                txtUsername.onkeyup = checkIfUsernameAvailable;

                function ConfirmPassword() {
                    txtConfirmPassword.setCustomValidity("");
                    if (txtPassword.value != txtConfirmPassword.value) {
                        txtConfirmPassword.setCustomValidity("Passwords do not match.");
                    }
                }

                function checkIfUsernameAvailable() {
                    txtUsername.setCustomValidity("");
                    $.ajax({
                        method: 'POST',
                        url: '/Users/checkIfUsernameExist',
                        data: { Username: txtUsername.value }
                    }).done(function (data) {
                        if (data != "OK") {
                            console.log("*" + data + "*");
                            txtUsername.setCustomValidity("Username Taken");
                        }
                    })

                    

                }

            }
        </script>
        @if (ViewBag.Error != null)
        {
            <div class="text-danger">@ViewBag.Error</div>
        }
    </div>
</div>

<div>
    Already registered? <a asp-action="Login">Click here</a> to login
</div>

@section Scripts {
    <script src="~/js/Users/CustomerRegister.js"></script>
}

vapor/Views/Users/RegisterDeveloper.cshtml
@model vapor.Models.User

@{
    ViewData["Title"] = "Register Developer";
}

<h1>Register a new Developer</h1>


<div class="row d-flex justify-content-center">
    <div class="col-md-4">
        <form id="register-user">
            <div class="row">
                <div class="form-group">
                    <input type="text" class="form-control" placeholder="First Name" id="register-firstname" name="firstName" required>
                </div>
            </div>
            <div class="row">
                <div class="form-group">
                    <input type="text" class="form-control" placeholder="Last Name" id="register-lastname" name="lastName" required>
                </div>
            </div>
            <div class="row">
                <div class="form-group">
                    <input type="text" class="form-control" placeholder="User Name" id="register-username" name="Username" required>
                </div>
            </div>
            <div class="row">
                <div class="form-group">
                    <input type="password" class="form-control" placeholder="Password" id="register-password" name="Password" required>
                </div>
            </div>
            <div class="row">
                <div class="form-group">
                    <input type="password" class="form-control" placeholder="Password Again" id="register-password-again" name="PasswordAgain" required>
                </div>
            </div>
            <div class="row">
                <select class="form-control" name="type" hidden required>
                    <option value="1">Developer</option>
                </select>
                <span class="text-danger"></span>
            </div>
            <div class="row">
                <div class="form-group">
                    <input type="email" class="form-control" placeholder="Email" id="register-email" name="email" required>
                </div>
            </div>
            <div class="row">
                <div class="form-group">
                    <input type="text" class="form-control" placeholder="Phone Number" id="register-phonenumber" name="phoneNumber" required>
                </div>
            </div>
            <div class="row">
                <div class="form-group">
                    <label class="control-label">Developer Avatar</label>
                    <input name="developerAvater" class="form-control-file" type="file" id="register-avatar" required />
                </div>
            </div>

            <div class="form-group">
                <button class="btn btn-primary" id="register-btn">Register</button>
            </div>
        </form>
        <script type="text/javascript">
            window.onload = function () {
                var txtPassword = document.getElementById("register-password");
                var txtConfirmPassword = document.getElementById("register-password-again");
                txtPassword.onchange = ConfirmPassword;
                txtConfirmPassword.onkeyup = ConfirmPassword;

                var txtUsername = document.getElementById("register-username");
                console.log(txtUsername);
                txtUsername.onkeyup = checkIfUsernameAvailable;

                function ConfirmPassword() {
                    txtConfirmPassword.setCustomValidity("");
                    if (txtPassword.value != txtConfirmPassword.value) {
                        txtConfirmPassword.setCustomValidity("Passwords do not match.");
                    }
                }

                function checkIfUsernameAvailable() {
                    txtUsername.setCustomValidity("");
                    $.ajax({
                        method: 'POST',
                        url: '/Users/checkIfUsernameExist',
                        data: { Username: txtUsername.value }
                    }).done(function (data) {
                        if (data != "OK") {
                            console.log("*" + data + "*");
                            txtUsername.setCustomValidity("Username Taken");
                        }
                    })



                }

            }
        </script>
        @if (ViewBag.Error != null)
        {
            <div class="text-danger">@ViewBag.Error</div>
        }
    </div>
</div>

<div>
    Already registered? <a asp-action="Login">Click here</a> to login
</div>

@section Scripts {
    <script src="~/js/Users/DeveloperRegister.js"></script>
}